pipeline {

    agent any
    stages {

	        stage('Checkout Codebase'){
	            steps{
	                cleanWs()
	                checkout scm: [$class: 'GitSCM', branches: [[name: '*/main']],userRemoteConfigs:
	                [[credentialsId: 'github-ssh-key-1', url: 'git@github.com:Bastur/595Test2.git']]]
	            }
	        }
		
		stage('Build') {
	                sh "chmod +x -R ./HelloWorld"
	                sh "javac ./HelloWorld/src/HelloWorld.java"
	            }
	        }
	
		stage('Run') {
	                sh "javac ./HelloWorld/src/HelloWorld.java"
	            }
	        }
		
		stage('Email Notification') {
	                mail bcc: '', body: 'You\'re Jenkins Project has run successfully', cc: '', from: '', replyTo: '', subject: 'Jenkins Project', to: 'mmedina117@toromail.csudh.edu'
            }
        }
	}
}
